server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gachicar
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: DEBUG

jwt:
  secret: Z2FjaGljYXJQcm9qZWN0aW5Tb29rbXl1bmcxOTE5MjA=