server:
  port: 9090
  undertow:
    # HTTP 설정
    http2:
      enabled: true # HTTP/2 지원 여부
    direct-buffers: true # 다이렉트 버퍼 사용 여부
    buffer-size: 1024 # 버퍼 크기

    websocket:
      direct-buffers: true
      buffer-size: 1024

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gachicar
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: DEBUG

jwt:
  secret: Z2FjaGljYXJQcm9qZWN0aW5Tb29rbXl1bmcxOTE5MjA=